### PR TITLE
Api/v1

### PR DESCRIPTION
**Pull request by jeanjoe**
API V1 contains API endpoints, and tests

### CODE REVIEW

**Comment by kyakusahmed** [comment]
i love your work but i didnt see any doc strings or comments through  most of file codes
i hope u check that

**Comment by jeanjoe** [comment]
Thanks @kyakusahmed for pointing that out, I have added the doc strings

**Comment by Ivankivu** [comment]
@jeanjoe please share a link to your Heroku app so we can see the API in action

**Comment by jeanjoe** [comment]
@ALL I have updated the README.md with the Heroku link

**Pull request merged**
